#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Mon Mar 27 23:24:29 CST 2017
# Module: docker
# Submodule:
# Command: version
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
module_version="1.0.0"
###############################################################################

function run() {
    
    git log --pretty='v0.0.0 %ci %H' | head -n 1 | while read ver dt tm tz hs; do
        ts_date=${dt/\-/}
        ts_date=${ts_date/\-/}
        ts_time=${tm/\:/}
        ts_time=${ts_time/\:/}
        ts_hash=$(echo $hs | awk '{print substr($1,0,12)}')
        echo ${ver}-${ts_date}${ts_time}-${ts_hash}
    done

    echo ""
    
}

###############################################################################
